[versions]
micronaut = "5.2.0"
micrometer = "1.16.7"
rewrite-micronaut = "2.36.0"

[libraries]
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
micronaut-rewrite = { module = 'org.openrewrite.recipe:rewrite-micronaut', version.ref = 'rewrite-micronaut' }
micrometer-core = { module = 'io.micrometer:micrometer-core', version.ref = 'micrometer' }

[bundles]

[plugins]
